### ISSUE TITLE
Builder-free runtime usage

### ISSUE THREAD

**Issue by jondo2010** [jondo2010/boomerang#41]
`boomerang_runtime` has already been constructed in a way to have zero dependencies on other boomerang crates. However, it is currently not possible to separate out the build from the scheduler inputs

It should be possible for end-user crates to build a binary that does not include any code or deps from `boomerang_builder`.

```toml
[dependencies]
boomerang_runtime = "*"

[dev-dependencies]
boomerang_builder = "*"
```

The vision here is that the "builder" functionality is only a dev dependency.

This will require some additional layer of proc macro, some `build.rs` file, or some combination.
